[package]
name = "gers"
version = "0.1.0"
authors = ["Willem Victor <wimpievictor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
rust-wren = { version = "*", git = "https://gitlab.com/vangroan/rust-wren.git", branch="feature/docs" }
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_warn"] }
slog-async = "2.5"
slog-scope = "4.3"
slog-stdlog = "4.1"
slog-term = "2.6"
winit = "0.24"
